spring.datasource.url=jdbc:mysql://global_mysql_server:3306/smart_cafe_management?useSSL=false&serverTimezone=Asia/Ho_Chi_Minh&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root_super_password

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=codegymintern@gmail.com
spring.mail.password=zvhw hbdd omvl kvvx
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

cloudinary.cloud-name=xqkvkmdf
cloudinary.api-key=517593117344332
cloudinary.api-secret=SH-O5ragf0ycan6W-jh66L68IBc

spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml

paypal.client-id=AeX77BfVGcQ6NJO-3lbPvucOi_vpAXm2PvFw3y9tXI2_cTConRcta8nfXiqe9jNKIx35RcWArnz8e-oX
paypal.client-secret=EEekp5TuMPZUXJ4Od1VK6cRr3XjtrV7P4vu0dvdfSrNCadLhxzqV0rgQkZG_5SsE9XtiNTmJWQ6uBgM2
paypal.mode=sandbox

spring.data.redis.host=ideal-lemur-106829.upstash.io
spring.data.redis.port=6379
spring.data.redis.password=gQAAAAAAAaFNAAIgcDJmYjU5NWVhNzU1NDg0YmQ4ODM3NTU4ZWNmOGFiZmYxYg
spring.data.redis.ssl.enabled=true

groq.api.key=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
groq.api.url=https://api.groq.com/openai/v1/chat/completions
groq.api.model=qwen/qwen3.6-27b